import { vazir } from "@/assets/fonts/vazirFont";
import "@/assets/style/global.css";
import Header from "@/components/Header/Header";
import { Providers } from "@/components/Providers/Providers";

export const metadata = {
	title: "2Create Next App",
	description: "2Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="fa" dir="rtl" style={{ fontSize: "16px" }}>
			<body className={`${vazir.variable} font-vazir pt-14`}>
				<Providers>
					<Header />
					{children}
				</Providers>
			</body>
		</html>
	);
}
