import { iranSans } from "@/assets/fonts/iranSansFont";
import "@/assets/style/global.css";

export const metadata = {
	title: "2Create Next App",
	description: "2Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${iranSans.variable} font-iransans`}>
				<div>asd;lfkjasd;flkjj</div>
				{children}
			</body>
		</html>
	);
}
