

import RegisterForm from "@/app/(loginRegister)/(components)/RegisterForm";
import { FC } from "react";

export const metadata = {
	title: "hello",
	description: "2Generated by create next app",
};

const Register: FC = () => {
	return <div className="px-6 py-10">
		<RegisterForm/>
	</div>;
};

export default Register;
