"use client";
import { Tab, TabList, Tabs } from "@chakra-ui/react";
import { usePathname, useRouter } from "next/navigation";
import routes from "@/global/constants/routes";
import { FiUserCheck, FiUserPlus } from "react-icons/fi";

export const metadata = {
	title: "hello",
	description: "2Generated by create next app",
};

const tabNames = { "/login": 0, "/register": 1 };

const LoginRegisterTab = ({
	children,
}: {
	children: React.ReactNode;
}) => {
	//hooks
	const pathname = usePathname();
	const { push } = useRouter();

	//functions
	const handleTabChange = (index: number) => {
		if (index === 0) push(routes.login.path);
		if (index === 1) push(routes.register.path);
	};

	return (
		<div className="">
			<Tabs
				align="center"
        size="lg"
        colorScheme="red"
				index={tabNames[pathname as "/login" | "/register"]}
				onChange={handleTabChange}
			>
				<TabList>
					<Tab>
						<FiUserCheck className="ml-2" /> ورود به حساب
					</Tab>
					<Tab>
						<FiUserPlus className="ml-2" /> ایجاد حساب
					</Tab>
				</TabList>
				{children}
			</Tabs>
		</div>
	);
};

export default LoginRegisterTab;
