import Button from "@/components/Button";
import { FC } from "react";

export const metadata = {
	title: "hello",
	description: "2Generated by create next app",
};

const Hello: FC = () => {
	return (
		<div className="mt-6 text-xl text-sky-500">
			سلام <br />
			<Button />
		</div>
	);
};

export default Hello;
